export const MOVIE_FETCH_STARTED = 'MOVIE_FETCH_STARTED';
export const MOVIE_FETCH_FAILED = 'MOVIE_FETCH_FAILED';
export const MOVIE_FETCH_FINISHED = 'MOVIE_FETCH_FINISHED';
export const MOVIE_DETAILS_OPEN = 'MOVIE__DETAILS_OPEN';

export const MOVIES_FETCH_STARTED = 'MOVIES_FETCH_STARTED';
export const MOVIES_FETCH_FAILED = 'MOVIES_FETCH_FAILED';
export const MOVIES_FETCH_FINISHED = 'MOVIES_FETCH_FINISHED';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const NAVIGATION_OPEN = 'NAVIGATION_OPEN';
export const SET_PAGE = 'SET_PAGE';

// ------------ UNDER DEVELOPMENT ------------

// export const FILTERACTIVE = 'FILTERACTIVE';
// export const SET_FILTERS = 'SET_FILTERS';
